services:
    monolog.processor.request:
        class: SWP\AnalyticsBundle\Processor\RequestProcessor
        arguments:  [ @session ]
        tags:
            - { name: monolog.processor, method: processRecord }
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest}

    logger_database:
        class: SWP\AnalyticsBundle\Logger\DatabaseHandler
        calls:
            - [ setContainer, [ @service_container ] ]
