SWP\Bundle\TemplateEngineBundle\Model\WidgetModelBranch:
    type: entity
    table: swp_widgetmodel_branch
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    fields:
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            nullable: true
            gedmo:
                timestampable:
                    on: update
    oneToOne:
        source:
            targetEntity: WidgetModel
        target:
            targetEntity: WidgetModel
